[package]
name = "actix-web-template"
version = "0.1.0"
authors = ["Bruno Rocha <rochacbruno@gmail.com>"]

[dependencies]
env_logger = "0.5"
actix = "0.5"
actix-web = "^0.6"
askama = "0.6"

[build-dependencies]
askama = "0.6"
